### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by cptrodgers**

### CODE REVIEW

**Comment by cptrodgers** [comment]
Can we change the merge option from merge -> squash and merge.
@vertexclique

**Review by vertexclique — COMMENTED** [review]
You don't need to bump the version in Cargo.toml. `cargo release patch` will bump them. Just add docstrings in this one. After merging you can run it.

I will change the merge options.

**Comment by cptrodgers** [comment]
Updated.

**Review by vertexclique — APPROVED** [review]
Thanks, shipping it! 🚀

**Pull request merged**
